gg.jte.usePrecompiledTemplates=true
spring.application.name=chemtools.app
spring.profiles.active=desktop
server.port=0
logging.level.org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping=TRACE
logging.level.gg.jte=TRACE
logging.level.org.springframework.web.servlet.view=TRACE
logging.level.org.springframework.boot.autoconfigure=DEBUG